# Generated by Django 5.1 on 2024-10-25 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_create_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('frontend', '프론트엔드'), ('backend', '백엔드'), ('data-structures', '자료구조'), ('algorithms', '알고리즘'), ('operating-systems', '운영체제'), ('architecture', '아키텍처'), ('network', '네트워크'), ('database', '데이터베이스'), ('machine-learning', '머신러닝'), ('statistics', '수리통계'), ('review', '회고'), ('career', '커리어'), ('fitness', '헬스')], default='frontend', max_length=20),
        ),
    ]
