name: Deploy to Cloud Run

on:
  push:
    branches:
      - main  # 배포를 트리거할 브랜치

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Google Cloud 인증
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          token_audience: 'sts.googleapis.com'  # Audience 명시적으로 설정
          create_credentials_file: true
          workload_identity_provider: 'projects/${{ secrets.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/${{ secrets.GCP_POOL_ID }}/providers/${{ secrets.GCP_PROVIDER_ID }}'
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}

      # 3. GCP SDK 설정
      - name: Setup GCP SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          credentials_file_path: ${{ steps.auth.outputs.credentials_file_path }}  # 인증 파일 경로 지정

      # 4. Artifact Registry를 위한 Docker 인증 설정
      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker asia-northeast3-docker.pkg.dev

      # 5. Docker 이미지 빌드
      - name: Build Docker image
        run: |
          cd backend/plast-blog  # Dockerfile이 위치한 디렉토리로 이동
          docker build -t plast-blog .

      # 6. Docker 이미지 태그 지정
      - name: Tag Docker image
        run: |
          docker tag plast-blog asia-northeast3-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/docker-repo/plast-blog:latest

      # 7. Docker 이미지 Artifact Registry에 푸시
      - name: Push Docker image to Artifact Registry
        run: |
          docker push asia-northeast3-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/docker-repo/plast-blog:latest

      # 8. Cloud Run에 배포
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy plast-blog \
            --image asia-northeast3-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/docker-repo/plast-blog:latest \
            --region asia-northeast3 \
            --platform managed \
            --allow-unauthenticated
