name: Deploy to Cloud Run

on:
  push:
    branches:
      - main  # 배포를 트리거할 브랜치

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Cloud SDK
      - name: Setup GCP SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true

      # Docker 인증 설정
      - name: Configure Docker for Artifact Registry
        run: |
          echo ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }} | docker login -u _json_key --password-stdin https://us-central1-docker.pkg.dev

      # Docker 이미지 빌드
      - name: Build Docker image
        run: |
          cd backend/plast-blog
          docker build -t my-django-app .

      # Docker 이미지 태그 지정
      - name: Tag Docker image
        run: |
          docker tag my-django-app us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/my-django-app/my-django-app:latest

      # Docker 이미지 푸시
      - name: Push Docker image to Artifact Registry
        run: |
          docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/my-django-app/my-django-app:latest

      # Cloud Run에 배포
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy my-django-app \
            --image us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/my-django-app/my-django-app:latest \
            --region ${{ secrets.GCP_REGION }} \
            --platform managed \
            --allow-unauthenticated
