name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

# fixing
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          create_credentials_file: true
          workload_identity_provider: 'projects/${{ secrets.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/${{ secrets.GCP_POOL_ID }}/providers/${{ secrets.GCP_PROVIDER_ID }}'
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}

      - name: Setup GCP SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT }}

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker asia-northeast3-docker.pkg.dev

      - name: Build Docker image
        run: |
          cd backend
          docker build -t plast-blog .

      - name: Tag Docker image
        run: |
          docker tag plast-blog asia-northeast3-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/docker-repo/plast-blog:latest

      - name: Push Docker image to Artifact Registry
        run: |
          docker push asia-northeast3-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/docker-repo/plast-blog:latest

      - name: Download Cloud SQL Proxy
        run: |
          curl -o cloud-sql-proxy https://storage.googleapis.com/cloud-sql-connectors/cloud-sql-proxy/v2.13.0/cloud-sql-proxy.linux.amd64
          chmod +x cloud-sql-proxy

      - name: Start Cloud SQL Proxy
        run: |
          ./cloud-sql-proxy -instances=${{ secrets.DATABASE_HOST }}=tcp:5432 &

      - name: Wait for Cloud SQL Proxy to start
        run: |
          sleep 10

      - name: Run Django Migrations
        env:
          DATABSE_NAME: ${{ secrets.DATABASE_NAME }}
          DATABASE_USER: ${{ secrets.DATABASE_USER }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          DATABASE_HOST: 127.0.0.1
          DATABASE_PORT: 5432
          DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
          DJANGO_DEBUG: ${{ secrets.DJANGO_DEBUG }}
          DJANGO_ALLOWED_HOSTS: ${{ secrets.DJANGO_ALLOWED_HOSTS }}
        run: |
          docker run --rm \
            -e DATABASE_NAME=${DATABASE_NAME} \
            -e DATABASE_USER=${DATABASE_USER} \
            -e DATABASE_PASSWORD=${DATABASE_PASSWORD} \
            -e DATABASE_HOST=${DATABASE_HOST} \
            -e DATABASE_PORT=${DATABASE_PORT} \
            -e DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY} \
            -e DJANGO_DEBUG=${DJANGO_DEBUG} \
            -e DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS} \
            asia-northeast3-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/docker-repo/plast-blog:latest \
            python manage.py migrate

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy plast-blog \
            --image asia-northeast3-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/docker-repo/plast-blog:latest \
            --region asia-northeast3 \
            --platform managed \
            --allow-unauthenticated \
            --update-env-vars=^#^DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }},DJANGO_DEBUG=${{ secrets.DJANGO_DEBUG }},DJANGO_ALLOWED_HOSTS=${{ secrets.DJANGO_ALLOWED_HOSTS }},DATABASE_NAME=${{ secrets.DATABASE_NAME }},DATABASE_USER=${{ secrets.DATABASE_USER }},DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }},DATABASE_HOST=/cloudsql/${{ secrets.DATABASE_HOST }}
